from typing import Dict, Any, Optional, List, Deque
from collections import deque
from enum import Enum

class CircuitState(Enum):
    CLOSED = "CLOSED"
    OPEN = "OPEN"
    HALF_OPEN = "HALF_OPEN"

class CacheEntry:
    data: Any
    timestamp: float

    def __init__(self, data: Any, timestamp: float) -> None: ...

class SpaceTradersClient:
    base_url: str
    token: Optional[str]
    logger: Any
    requests_per_second: float
    min_request_interval: float
    burst_limit: int
    request_timestamps: Deque[float]
    response_times: Deque[float]
    rate_adjustment_threshold: float
    rate_adjustment_interval: float
    last_rate_adjustment: Optional[float]
    error_threshold: int
    success_threshold: int
    reset_timeout: float
    circuit_state: CircuitState
    error_count: int
    success_count: int
    last_error_time: Optional[float]
    error_history: List[Dict[str, Any]]
    cache_ttl: float
    _cache: Dict[str, CacheEntry]
    request_count: int

    def __init__(self, token: Optional[str] = None) -> None: ...
    
    def _make_request(self, method: str, endpoint: str, data: Optional[Dict[str, Any]] = None, **kwargs) -> Dict[str, Any]: ...
    def _wait_for_rate_limit(self) -> None: ...
    def _log_response(self, response: Any, duration: float) -> None: ...
    def _handle_request_error(self, error: Exception, endpoint: str) -> None: ...
    def _update_circuit_state(self, success: bool, endpoint: str) -> None: ...
    def _check_circuit_breaker(self, endpoint: str) -> bool: ...
    
    def register_new_agent(self, agent_symbol: str, faction: str = "COSMIC") -> Dict[str, Any]: ...
    def get_agent(self) -> Dict[str, Any]: ...
    def get_contracts(self) -> Dict[str, Any]: ...
    def get_ship(self, ship_symbol: str) -> Dict[str, Any]: ...
    def get_my_ships(self) -> Dict[str, Any]: ...
    def get_ship_nav(self, ship_symbol: str) -> Dict[str, Any]: ...
    def get_waypoints(self, system_symbol: str) -> Dict[str, Any]: ...
    def get_market(self, system: str, waypoint: str) -> Dict[str, Any]: ...
    def get_systems(self) -> Dict[str, Any]: ...
    def get_system_info(self, system_symbol: str) -> Dict[str, Any]: ...
    def get_ships_with_info(self, system: str, waypoint: str) -> Dict[str, Any]: ...
    def get_factions(self) -> Dict[str, Any]: ...
    def get_waypoint(self, system: str, waypoint: str) -> Dict[str, Any]: ...
    def get_system_waypoints(self, system_symbol: str) -> Dict[str, Any]: ...
    def get_ships(self) -> Dict[str, Any]: ...
    
    def purchase_ship(self, ship_type: str, waypoint_symbol: str) -> Dict[str, Any]: ...
    def orbit_ship(self, ship_symbol: str) -> Dict[str, Any]: ...
    def navigate_ship(self, ship_symbol: str, waypoint_symbol: str) -> Dict[str, Any]: ...
    def dock_ship(self, ship_symbol: str) -> Dict[str, Any]: ...
    def refuel_ship(self, ship_symbol: str) -> Dict[str, Any]: ...
    def extract_resources(self, ship_symbol: str) -> Dict[str, Any]: ...
    def sell_goods(self, ship_symbol: str, good_symbol: str, units: int) -> Dict[str, Any]: ...
    def buy_goods(self, ship_symbol: str, good_symbol: str, units: int) -> Dict[str, Any]: ...
    def transfer_cargo(self, from_ship: str, to_ship: str, good_symbol: str, units: int) -> Dict[str, Any]: ...
    def scan_ships(self, ship_symbol: str) -> Dict[str, Any]: ...
    def negotiate_contract(self, ship_symbol: str) -> Dict[str, Any]: ...
    def repair_ship(self, ship_symbol: str) -> Dict[str, Any]: ...
    def jump_ship(self, ship_symbol: str, system_symbol: str) -> Dict[str, Any]: ...
    def get_ship_cooldown(self, ship_symbol: str) -> Dict[str, Any]: ...
    def get_ship_mounts(self, system: str, waypoint: str) -> Dict[str, Any]: ...
    def get_shipyard(self, system: str, waypoint: str) -> Dict[str, Any]: ...
    def purchase_ship_module(self, ship_symbol: str, module_symbol: str) -> Dict[str, Any]: ...
    def accept_contract(self, contract_id: str) -> Dict[str, Any]: ...
