from typing import Dict, Any, List, Optional

class SpaceTradersClient:
    token: str
    error_count: int
    request_count: int

    def __init__(self, token: str) -> None: ...
    
    def get_contracts(self) -> Dict[str, Any]: ...
    def negotiate_contract(self, ship_symbol: str) -> Dict[str, Any]: ...
    def accept_contract(self, contract_id: str) -> Dict[str, Any]: ...
    def get_my_ships(self) -> Dict[str, Any]: ...
    def get_ship(self, ship_symbol: str) -> Dict[str, Any]: ...
    def get_ship_nav(self, ship_symbol: str) -> Dict[str, Any]: ...
    def get_ship_cooldown(self, ship_symbol: str) -> Dict[str, Any]: ...
    def extract_resources(self, ship_symbol: str) -> Dict[str, Any]: ...
    def get_ship_mounts(self, system: str, waypoint: str) -> Dict[str, Any]: ...
    def get_waypoints(self, system: str) -> Dict[str, Any]: ...
    def get_market(self, system: str, waypoint: str) -> Dict[str, Any]: ...
    def dock_ship(self, ship_symbol: str) -> Dict[str, Any]: ...
    def refuel_ship(self, ship_symbol: str) -> Dict[str, Any]: ...
    def repair_ship(self, ship_symbol: str) -> Dict[str, Any]: ...
    def jump_ship(self, ship_symbol: str, system: str) -> Dict[str, Any]: ...
    def get_systems(self) -> Dict[str, Any]: ...
    def get_agent(self) -> Dict[str, Any]: ...
    def get_shipyard(self, system: str, waypoint: str) -> Dict[str, Any]: ...
    def purchase_ship(self, ship_type: str, waypoint: str) -> Dict[str, Any]: ...
    def navigate_ship(self, ship_symbol: str, waypoint: str) -> Dict[str, Any]: ...
    def purchase_ship_module(self, ship_symbol: str, module_symbol: str) -> Dict[str, Any]: ...
