from typing import Dict, Any, Optional
from threading import Timer, Lock

class StateManager:
    db_path: str
    save_interval: int
    last_hash: Optional[str]
    lock: Lock
    timer: Optional[Timer]

    def __init__(self, db_path: str = 'agent_state.db', save_interval: int = 300) -> None: ...
    
    def save_state(self, state: Dict[str, Any]) -> None: ...
    def get_latest_state(self) -> Optional[Dict[str, Any]]: ...
    def save_if_changed(self) -> None: ...
    def cleanup_old_states(self, keep_days: int = 7) -> None: ...
    def stop(self) -> None: ...
