from typing import Dict, Any, Optional

class StateManager:
    def __init__(self, filename: str) -> None: ...
    
    def save_state(self, state: Dict[str, Any]) -> None: ...
    def get_latest_state(self) -> Optional[Dict[str, Any]]: ...
    def save_if_changed(self) -> None: ...
    def load_state(self) -> Optional[Dict[str, Any]]: ...
